Added training pipeline kustomization
TODO:
The job still fails with the following error:

ImportError: cannot import name 'examples' from partially initialized module 'altair' (most likely due to a circular import)

This is likely due to unresolved mlflow dependencies.